language: node_js
node_js:
    - '6'
    - '8'
    - '9'
    - '10'
sudo: false
env:
    - FORCE_COLOR=true

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
    only:
        - master
        - type != push

script:
    - npm run $COMMAND
    - npm link
    - gh

jobs:
    include:
        - stage: test
          env: COMMAND=test:ci
        - stage: release
          node_js: lts/*
          env: COMMAND=semantic-release

stages:
    - test
    - name: release
      if: branch = master AND type IN (push)
